/* This file is part of nut.
 * 
 * Copyright (c) 2015, Alexandre Monti
 * 
 * nut is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * nut is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with nut.  If not, see <http://www.gnu.org/licenses/>.
 */

type_specifier     := IDENTIFIER?type
                   
argument_list      := LEFT_PAREN (type_specifier IDENTIFIER (type_specifier IDENTIFIER)*)? RIGHT_PAREN
                   
function_call_expr := IDENTIFIER?function expression_list
                   
expression         :=
                   
expression_list    := LEFT_PAREN (expression (COMMA expression)*)? RIGHT_PAREN
                   
declaration_stmt   := type_specifier IDENTIFIER (EQUALS expression)? SEMICOLON
                   
assignment_stmt    := IDENTIFIER?variable EQUALS expression SEMICOLON
                   
function_call_stmt := function_call SEMICOLON
                   
statement          := declaration_stmt
                    | assignment_stmt
                    | function_call_stmt
                   
statement_block    := LEFT_CURLY statement* RIGHT_CURLY
                   
function_decl      := type_specifier IDENTIFIER
                      LEFT_PAREN argument_list RIGHT_PAREN
                      statement_block
